# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Joumongo\Documents\Economystique\account.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_account(object):
    def setupUi(self, account):
        account.setObjectName("account")
        account.resize(1600, 900)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("c:\\Users\\Joumongo\\Documents\\Economystique\\img/econoLogo2.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        account.setWindowIcon(icon)
        account.setStyleSheet("color: black;")
        self.lblBusinessName_2 = QtWidgets.QLabel(account)
        self.lblBusinessName_2.setGeometry(QtCore.QRect(650, 30, 311, 91))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(22)
        self.lblBusinessName_2.setFont(font)
        self.lblBusinessName_2.setStyleSheet("border: 0px solid white;\n"
"background: #365b6d;\n"
"color: white;\n"
"border-radius: 25px;")
        self.lblBusinessName_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lblBusinessName_2.setObjectName("lblBusinessName_2")
        self.frame = QtWidgets.QFrame(account)
        self.frame.setGeometry(QtCore.QRect(0, 0, 1601, 61))
        self.frame.setStyleSheet("background: #365b6d;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.btnSales = QtWidgets.QPushButton(self.frame)
        self.btnSales.setGeometry(QtCore.QRect(1312, 0, 111, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnSales.setFont(font)
        self.btnSales.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnSales.setStyleSheet("QPushButton {\n"
"    background-color: #365b6d;\n"
"    color: white;\n"
"    border-radius: 50px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #5b8ca4;\n"
"}\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background-color: #365b6d;\n"
"}\n"
"")
        self.btnSales.setObjectName("btnSales")
        self.btnInventory = QtWidgets.QPushButton(self.frame)
        self.btnInventory.setGeometry(QtCore.QRect(1202, 0, 111, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnInventory.setFont(font)
        self.btnInventory.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnInventory.setStyleSheet("QPushButton {\n"
"    background-color: #365b6d;\n"
"    color: white;\n"
"    border-radius: 50px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #5b8ca4;\n"
"}\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background-color: #365b6d;\n"
"}\n"
"")
        self.btnInventory.setObjectName("btnInventory")
        self.btnPOS = QtWidgets.QPushButton(self.frame)
        self.btnPOS.setGeometry(QtCore.QRect(1422, 0, 111, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnPOS.setFont(font)
        self.btnPOS.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnPOS.setStyleSheet("QPushButton {\n"
"    background-color: #365b6d;\n"
"    color: white;\n"
"    border-radius: 50px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #5b8ca4;\n"
"}\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background-color: #365b6d;\n"
"}\n"
"")
        self.btnPOS.setObjectName("btnPOS")
        self.btnAccount = QtWidgets.QPushButton(self.frame)
        self.btnAccount.setGeometry(QtCore.QRect(1530, 0, 71, 61))
        self.btnAccount.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnAccount.setStyleSheet("QPushButton {\n"
"    background-color: #365b6d;\n"
"    color: white;\n"
"    border-radius: 50px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #5b8ca4;\n"
"}\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background-color: #365b6d;\n"
"}\n"
"")
        self.btnAccount.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("c:\\Users\\Joumongo\\Documents\\Economystique\\img/pfBtn.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        self.btnAccount.setIcon(icon1)
        self.btnAccount.setIconSize(QtCore.QSize(50, 50))
        self.btnAccount.setObjectName("btnAccount")
        self.btnDashboard = QtWidgets.QPushButton(self.frame)
        self.btnDashboard.setGeometry(QtCore.QRect(0, 0, 291, 61))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(22)
        self.btnDashboard.setFont(font)
        self.btnDashboard.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnDashboard.setStyleSheet("QPushButton {\n"
"    background-color: #365b6d;\n"
"    color: white;\n"
"    border-radius: 50px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #5b8ca4;\n"
"}\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background-color: #365b6d;\n"
"}\n"
"")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("c:\\Users\\Joumongo\\Documents\\Economystique\\img/econologo_transparent_cropped.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnDashboard.setIcon(icon2)
        self.btnDashboard.setIconSize(QtCore.QSize(30, 30))
        self.btnDashboard.setObjectName("btnDashboard")
        self.frame_3 = QtWidgets.QFrame(account)
        self.frame_3.setGeometry(QtCore.QRect(20, 160, 1561, 641))
        self.frame_3.setStyleSheet("#frame_3{\n"
"    border-radius: 5px;\n"
"    background: rgba(0,0,0,128);\n"
"}")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.frame_2 = QtWidgets.QFrame(self.frame_3)
        self.frame_2.setGeometry(QtCore.QRect(90, 390, 461, 161))
        self.frame_2.setAutoFillBackground(False)
        self.frame_2.setStyleSheet("#frame_2{\n"
"    background: rgba(0,0,0,150);\n"
"    border-radius: 10px;\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_2.setObjectName("frame_2")
        self.lblBsnsType = QtWidgets.QLabel(self.frame_2)
        self.lblBsnsType.setGeometry(QtCore.QRect(10, 10, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblBsnsType.setFont(font)
        self.lblBsnsType.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblBsnsType.setObjectName("lblBsnsType")
        self.lblIndustry = QtWidgets.QLabel(self.frame_2)
        self.lblIndustry.setGeometry(QtCore.QRect(10, 50, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblIndustry.setFont(font)
        self.lblIndustry.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblIndustry.setObjectName("lblIndustry")
        self.lblLocation = QtWidgets.QLabel(self.frame_2)
        self.lblLocation.setGeometry(QtCore.QRect(10, 90, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblLocation.setFont(font)
        self.lblLocation.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblLocation.setObjectName("lblLocation")
        self.lblBsnsTypeVal = QtWidgets.QLabel(self.frame_2)
        self.lblBsnsTypeVal.setGeometry(QtCore.QRect(150, 10, 301, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblBsnsTypeVal.setFont(font)
        self.lblBsnsTypeVal.setAlignment(QtCore.Qt.AlignCenter)
        self.lblBsnsTypeVal.setObjectName("lblBsnsTypeVal")
        self.lblIndVal = QtWidgets.QLabel(self.frame_2)
        self.lblIndVal.setGeometry(QtCore.QRect(150, 50, 301, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblIndVal.setFont(font)
        self.lblIndVal.setAlignment(QtCore.Qt.AlignCenter)
        self.lblIndVal.setObjectName("lblIndVal")
        self.lblLocVal = QtWidgets.QLabel(self.frame_2)
        self.lblLocVal.setGeometry(QtCore.QRect(150, 90, 301, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblLocVal.setFont(font)
        self.lblLocVal.setAlignment(QtCore.Qt.AlignCenter)
        self.lblLocVal.setWordWrap(True)
        self.lblLocVal.setObjectName("lblLocVal")
        self.lblBusinessName = QtWidgets.QLabel(self.frame_3)
        self.lblBusinessName.setGeometry(QtCore.QRect(90, 320, 461, 41))
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(14)
        self.lblBusinessName.setFont(font)
        self.lblBusinessName.setAutoFillBackground(False)
        self.lblBusinessName.setStyleSheet("")
        self.lblBusinessName.setAlignment(QtCore.Qt.AlignCenter)
        self.lblBusinessName.setObjectName("lblBusinessName")
        self.imgBusinessLogo = QtWidgets.QLabel(self.frame_3)
        self.imgBusinessLogo.setGeometry(QtCore.QRect(180, 20, 281, 271))
        self.imgBusinessLogo.setText("")
        self.imgBusinessLogo.setPixmap(QtGui.QPixmap("c:\\Users\\Joumongo\\Documents\\Economystique\\img/all_seasons_logo_trans.png"))
        self.imgBusinessLogo.setScaledContents(True)
        self.imgBusinessLogo.setObjectName("imgBusinessLogo")
        self.imgProfile = QtWidgets.QLabel(self.frame_3)
        self.imgProfile.setGeometry(QtCore.QRect(1130, 30, 261, 251))
        self.imgProfile.setText("")
        self.imgProfile.setPixmap(QtGui.QPixmap("c:\\Users\\Joumongo\\Documents\\Economystique\\img/profile.png"))
        self.imgProfile.setScaledContents(True)
        self.imgProfile.setObjectName("imgProfile")
        self.lblRole = QtWidgets.QLabel(self.frame_3)
        self.lblRole.setGeometry(QtCore.QRect(1150, 370, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lblRole.setFont(font)
        self.lblRole.setAlignment(QtCore.Qt.AlignCenter)
        self.lblRole.setObjectName("lblRole")
        self.lblUserName = QtWidgets.QLabel(self.frame_3)
        self.lblUserName.setGeometry(QtCore.QRect(1100, 320, 321, 41))
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(14)
        self.lblUserName.setFont(font)
        self.lblUserName.setAlignment(QtCore.Qt.AlignCenter)
        self.lblUserName.setObjectName("lblUserName")
        self.btnLogOut = QtWidgets.QPushButton(account)
        self.btnLogOut.setGeometry(QtCore.QRect(730, 820, 151, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnLogOut.setFont(font)
        self.btnLogOut.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnLogOut.setStyleSheet("color: white;\n"
"background-color: red;\n"
"\n"
"")
        self.btnLogOut.setFlat(False)
        self.btnLogOut.setObjectName("btnLogOut")
        self.frame_3.raise_()
        self.lblBusinessName_2.raise_()
        self.frame.raise_()
        self.btnLogOut.raise_()

        self.retranslateUi(account)
        QtCore.QMetaObject.connectSlotsByName(account)

    def retranslateUi(self, account):
        _translate = QtCore.QCoreApplication.translate
        account.setWindowTitle(_translate("account", "EconoMystique"))
        self.lblBusinessName_2.setText(_translate("account", "Account"))
        self.btnSales.setText(_translate("account", "Sales"))
        self.btnInventory.setText(_translate("account", "Inventory"))
        self.btnPOS.setText(_translate("account", "POS"))
        self.btnDashboard.setText(_translate("account", "EconoMystique"))
        self.lblBsnsType.setText(_translate("account", "<html><head/><body><p><span style=\" color:#ffffff;\">Business Type:</span></p></body></html>"))
        self.lblIndustry.setText(_translate("account", "<html><head/><body><p><span style=\" color:#ffffff;\">Industry:</span></p></body></html>"))
        self.lblLocation.setText(_translate("account", "<html><head/><body><p><span style=\" color:#ffffff;\">Location:</span></p></body></html>"))
        self.lblBsnsTypeVal.setText(_translate("account", "<html><head/><body><p><span style=\" color:#ffffff;\">Sole Propreitorship</span></p></body></html>"))
        self.lblIndVal.setText(_translate("account", "<html><head/><body><p><span style=\" color:#ffffff;\">Food (Pastries)</span></p></body></html>"))
        self.lblLocVal.setText(_translate("account", "<html><head/><body><p><span style=\" color:#ffffff;\">Del Rosario Bldg., Unit 2, Real Street, Magsaysay, Tagudin, Ilocos Sur</span></p></body></html>"))
        self.lblBusinessName.setText(_translate("account", "<html><head/><body><p><span style=\" color:#ffffff;\">All Seasons Cake Shop</span></p></body></html>"))
        self.lblRole.setText(_translate("account", "<html><head/><body><p><span style=\" color:#ffffff;\">Owner</span></p></body></html>"))
        self.lblUserName.setText(_translate("account", "<html><head/><body><p><span style=\" color:#ffffff;\">Kathlyn O. Lascota</span></p></body></html>"))
        self.btnLogOut.setText(_translate("account", "Log Out"))
