# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Joumongo\Documents\Economystique\add_item.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.NonModal)
        Dialog.resize(600, 475)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("c:\\Users\\Joumongo\\Documents\\Economystique\\img/econologo_bkgd 200.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        Dialog.setStyleSheet("background-color: #f4f4ec;")
        Dialog.setModal(False)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(10, 400, 581, 51))
        self.buttonBox.setStyleSheet("QPushButton{\n"
"    background: #365b6d;\n"
"    color: white;\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius:10px;\n"
"    border-color: black;\n"
"    padding: 5px;\n"
"    height: 25px;\n"
"    width: 100px;\n"
"    font-size: 16px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #53786d;\n"
"    border: 2px solid black;\n"
"}\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background-color: #365b6d;\n"
"}")
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 30, 132, 351))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.loParam = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.loParam.setContentsMargins(0, 0, 0, 0)
        self.loParam.setObjectName("loParam")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.loParam.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.loParam.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.loParam.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.loParam.addWidget(self.label_4)
        self.label_7 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.loParam.addWidget(self.label_7)
        self.label_8 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.loParam.addWidget(self.label_8)
        self.teInvID = QtWidgets.QLineEdit(Dialog)
        self.teInvID.setGeometry(QtCore.QRect(150, 30, 421, 41))
        self.teInvID.setStyleSheet("background: white;\n"
"border: 1px solid black;\n"
"border-radius: 5px;")
        self.teInvID.setAlignment(QtCore.Qt.AlignCenter)
        self.teInvID.setObjectName("teInvID")
        self.teDescription = QtWidgets.QLineEdit(Dialog)
        self.teDescription.setGeometry(QtCore.QRect(150, 90, 421, 41))
        self.teDescription.setStyleSheet("background: white;\n"
"border: 1px solid black;\n"
"border-radius: 5px;")
        self.teDescription.setAlignment(QtCore.Qt.AlignCenter)
        self.teDescription.setObjectName("teDescription")
        self.teBrand = QtWidgets.QLineEdit(Dialog)
        self.teBrand.setGeometry(QtCore.QRect(150, 150, 421, 41))
        self.teBrand.setStyleSheet("background: white;\n"
"border: 1px solid black;\n"
"border-radius: 5px;")
        self.teBrand.setAlignment(QtCore.Qt.AlignCenter)
        self.teBrand.setObjectName("teBrand")
        self.teUnit = QtWidgets.QLineEdit(Dialog)
        self.teUnit.setGeometry(QtCore.QRect(150, 210, 421, 41))
        self.teUnit.setStyleSheet("background: white;\n"
"border: 1px solid black;\n"
"border-radius: 5px;")
        self.teUnit.setAlignment(QtCore.Qt.AlignCenter)
        self.teUnit.setObjectName("teUnit")
        self.teAmount = QtWidgets.QLineEdit(Dialog)
        self.teAmount.setGeometry(QtCore.QRect(150, 270, 421, 41))
        self.teAmount.setStyleSheet("background: white;\n"
"border: 1px solid black;\n"
"border-radius: 5px;")
        self.teAmount.setAlignment(QtCore.Qt.AlignCenter)
        self.teAmount.setObjectName("teAmount")
        self.teROP = QtWidgets.QLineEdit(Dialog)
        self.teROP.setGeometry(QtCore.QRect(150, 330, 421, 41))
        self.teROP.setStyleSheet("background: white;\n"
"border: 1px solid black;\n"
"border-radius: 5px;")
        self.teROP.setAlignment(QtCore.Qt.AlignCenter)
        self.teROP.setObjectName("teROP")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Add Item"))
        self.label.setText(_translate("Dialog", "Inventory ID"))
        self.label_2.setText(_translate("Dialog", "Description"))
        self.label_3.setText(_translate("Dialog", "Brand"))
        self.label_4.setText(_translate("Dialog", "Unit"))
        self.label_7.setText(_translate("Dialog", "Quantity"))
        self.label_8.setText(_translate("Dialog", "Reoder Point"))
        self.teInvID.setPlaceholderText(_translate("Dialog", "Enter Item Inventory ID..."))
        self.teDescription.setPlaceholderText(_translate("Dialog", "Enter item description..."))
        self.teBrand.setPlaceholderText(_translate("Dialog", "Enter item brand..."))
        self.teUnit.setPlaceholderText(_translate("Dialog", "e.g. Kg, mL, etc..."))
        self.teAmount.setPlaceholderText(_translate("Dialog", "Enter positive number..."))
        self.teROP.setPlaceholderText(_translate("Dialog", "Enter positive number..."))
