# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Joumongo\Documents\Economystique\addCritical.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddCritical(object):
    def setupUi(self, AddCritical):
        AddCritical.setObjectName("AddCritical")
        AddCritical.resize(400, 210)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("c:\\Users\\Joumongo\\Documents\\Economystique\\img/econologo_bkgd 200.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        AddCritical.setWindowIcon(icon)
        AddCritical.setStyleSheet("background-color: #f4f4ec;")
        self.teAmount = QtWidgets.QTextEdit(AddCritical)
        self.teAmount.setGeometry(QtCore.QRect(40, 120, 301, 31))
        self.teAmount.setStyleSheet("background: #ffffff")
        self.teAmount.setFrameShape(QtWidgets.QFrame.Panel)
        self.teAmount.setTabChangesFocus(True)
        self.teAmount.setObjectName("teAmount")
        self.buttonBox = QtWidgets.QDialogButtonBox(AddCritical)
        self.buttonBox.setGeometry(QtCore.QRect(30, 170, 341, 32))
        self.buttonBox.setStyleSheet("QPushButton{\n"
"    background: #365b6d;\n"
"    color: white;\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius:10px;\n"
"    border-color: black;\n"
"    padding: 5px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #53786d;\n"
"    border: 2px solid black;\n"
"}\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background-color: #365b6d;\n"
"}")
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.lblCriticalItem = QtWidgets.QLabel(AddCritical)
        self.lblCriticalItem.setGeometry(QtCore.QRect(8, 15, 381, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblCriticalItem.setFont(font)
        self.lblCriticalItem.setText("")
        self.lblCriticalItem.setAlignment(QtCore.Qt.AlignCenter)
        self.lblCriticalItem.setObjectName("lblCriticalItem")
        self.lblAmount = QtWidgets.QLabel(AddCritical)
        self.lblAmount.setGeometry(QtCore.QRect(10, 90, 381, 21))
        self.lblAmount.setAlignment(QtCore.Qt.AlignCenter)
        self.lblAmount.setObjectName("lblAmount")
        self.label_3 = QtWidgets.QLabel(AddCritical)
        self.label_3.setGeometry(QtCore.QRect(140, 40, 111, 20))
        self.label_3.setStyleSheet("color: red;")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")

        self.retranslateUi(AddCritical)
        QtCore.QMetaObject.connectSlotsByName(AddCritical)

    def retranslateUi(self, AddCritical):
        _translate = QtCore.QCoreApplication.translate
        AddCritical.setWindowTitle(_translate("AddCritical", "Restock Critical Item"))
        self.teAmount.setHtml(_translate("AddCritical", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.lblAmount.setText(_translate("AddCritical", "Amount to Add"))
        self.label_3.setText(_translate("AddCritical", "Critical Item"))
