# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Joumongo\Documents\Economystique\addingWarning.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_stockWarning(object):
    def setupUi(self, stockWarning):
        stockWarning.setObjectName("stockWarning")
        stockWarning.resize(800, 500)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("c:\\Users\\Joumongo\\Documents\\Economystique\\img/econologo.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        stockWarning.setWindowIcon(icon)
        stockWarning.setStyleSheet("background: #f4f4ec;\n"
"color: black;\n"
"")
        self.tabItems = QtWidgets.QTableWidget(stockWarning)
        self.tabItems.setGeometry(QtCore.QRect(20, 90, 761, 241))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabItems.sizePolicy().hasHeightForWidth())
        self.tabItems.setSizePolicy(sizePolicy)
        self.tabItems.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        self.tabItems.setFont(font)
        self.tabItems.setStyleSheet("background: #ffffff")
        self.tabItems.setFrameShape(QtWidgets.QFrame.Panel)
        self.tabItems.setObjectName("tabItems")
        self.tabItems.setColumnCount(0)
        self.tabItems.setRowCount(0)
        self.btnClose = QtWidgets.QPushButton(stockWarning)
        self.btnClose.setGeometry(QtCore.QRect(640, 430, 125, 35))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.btnClose.setFont(font)
        self.btnClose.setStyleSheet("QPushButton{\n"
"    background: #365b6d;\n"
"    color: white;\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius:10px;\n"
"    border-color: black;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #53786d;\n"
"    border: 2px solid black;\n"
"}\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background-color: #365b6d;\n"
"}")
        self.btnClose.setObjectName("btnClose")
        self.label_3 = QtWidgets.QLabel(stockWarning)
        self.label_3.setGeometry(QtCore.QRect(20, 20, 761, 51))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: black;")
        self.label_3.setLineWidth(1)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.frame = QtWidgets.QFrame(stockWarning)
        self.frame.setGeometry(QtCore.QRect(20, 350, 601, 131))
        self.frame.setStyleSheet("#frame{\n"
"    border-radius: 5px;\n"
"    border: 1px solid black;\n"
"background-color: white;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.frame)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(9, 10, 581, 111))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lblWarning = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(14)
        self.lblWarning.setFont(font)
        self.lblWarning.setStyleSheet("background-color: white;")
        self.lblWarning.setText("")
        self.lblWarning.setAlignment(QtCore.Qt.AlignCenter)
        self.lblWarning.setWordWrap(True)
        self.lblWarning.setObjectName("lblWarning")
        self.verticalLayout.addWidget(self.lblWarning)
        self.btnAccept = QtWidgets.QPushButton(stockWarning)
        self.btnAccept.setGeometry(QtCore.QRect(640, 380, 125, 35))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.btnAccept.setFont(font)
        self.btnAccept.setStyleSheet("QPushButton{\n"
"    background: #365b6d;\n"
"    color: white;\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius:10px;\n"
"    border-color: black;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #53786d;\n"
"    border: 2px solid black;\n"
"}\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background-color: #365b6d;\n"
"}")
        self.btnAccept.setObjectName("btnAccept")

        self.retranslateUi(stockWarning)
        QtCore.QMetaObject.connectSlotsByName(stockWarning)

    def retranslateUi(self, stockWarning):
        _translate = QtCore.QCoreApplication.translate
        stockWarning.setWindowTitle(_translate("stockWarning", "Stocks Warning"))
        self.btnClose.setText(_translate("stockWarning", "Close"))
        self.label_3.setText(_translate("stockWarning", "Insufficient / Critical Items"))
        self.btnAccept.setText(_translate("stockWarning", "Accept"))
