# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Joumongo\Documents\Economystique\addPrExisting.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddPrExisting(object):
    def setupUi(self, AddPrExisting):
        AddPrExisting.setObjectName("AddPrExisting")
        AddPrExisting.resize(600, 300)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("c:\\Users\\Joumongo\\Documents\\Economystique\\img/econologo_bkgd 200.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        AddPrExisting.setWindowIcon(icon)
        AddPrExisting.setStyleSheet("background-color: #f4f4ec;")
        self.cbProducts = QtWidgets.QComboBox(AddPrExisting)
        self.cbProducts.setGeometry(QtCore.QRect(152, 31, 421, 45))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        self.cbProducts.setFont(font)
        self.cbProducts.setStyleSheet("background: white;\n"
"")
        self.cbProducts.setObjectName("cbProducts")
        self.buttonBox = QtWidgets.QDialogButtonBox(AddPrExisting)
        self.buttonBox.setGeometry(QtCore.QRect(20, 220, 561, 61))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        self.buttonBox.setFont(font)
        self.buttonBox.setStyleSheet("QPushButton{\n"
"    background: #365b6d;\n"
"    color: white;\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius:10px;\n"
"    border-color: black;\n"
"    padding: 5px;\n"
"    height: 25px;\n"
"    width: 100px;\n"
"    font-size: 16px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #53786d;\n"
"    border: 2px solid black;\n"
"}\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background-color: #365b6d;\n"
"}")
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayoutWidget = QtWidgets.QWidget(AddPrExisting)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 30, 131, 171))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.teAmount = QtWidgets.QLineEdit(AddPrExisting)
        self.teAmount.setGeometry(QtCore.QRect(150, 91, 421, 41))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        self.teAmount.setFont(font)
        self.teAmount.setStyleSheet("background: white;\n"
"border: 1px solid black;\n"
"border-radius: 5px;")
        self.teAmount.setAlignment(QtCore.Qt.AlignCenter)
        self.teAmount.setObjectName("teAmount")
        self.deExpDate = QtWidgets.QDateEdit(AddPrExisting)
        self.deExpDate.setGeometry(QtCore.QRect(150, 150, 421, 51))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        self.deExpDate.setFont(font)
        self.deExpDate.setStyleSheet("background: white;\n"
"border: 1px solid black;\n"
"border-radius: 5px;")
        self.deExpDate.setAlignment(QtCore.Qt.AlignCenter)
        self.deExpDate.setCalendarPopup(True)
        self.deExpDate.setObjectName("deExpDate")

        self.retranslateUi(AddPrExisting)
        QtCore.QMetaObject.connectSlotsByName(AddPrExisting)

    def retranslateUi(self, AddPrExisting):
        _translate = QtCore.QCoreApplication.translate
        AddPrExisting.setWindowTitle(_translate("AddPrExisting", "Add Existing Product"))
        self.label_3.setText(_translate("AddPrExisting", "Product"))
        self.label_4.setText(_translate("AddPrExisting", "Quantity"))
        self.label.setText(_translate("AddPrExisting", "Expiry Date"))
        self.teAmount.setPlaceholderText(_translate("AddPrExisting", "Enter a number..."))
