# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Joumongo\Documents\Economystique\critical.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_criticalItems(object):
    def setupUi(self, criticalItems):
        criticalItems.setObjectName("criticalItems")
        criticalItems.resize(800, 400)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("c:\\Users\\Joumongo\\Documents\\Economystique\\img/econologo_transparent_cropped.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        criticalItems.setWindowIcon(icon)
        criticalItems.setStyleSheet("background: #f4f4ec;")
        self.tabCritical = QtWidgets.QTableWidget(criticalItems)
        self.tabCritical.setGeometry(QtCore.QRect(20, 90, 761, 241))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabCritical.sizePolicy().hasHeightForWidth())
        self.tabCritical.setSizePolicy(sizePolicy)
        self.tabCritical.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        self.tabCritical.setFont(font)
        self.tabCritical.setStyleSheet("background: #ffffff")
        self.tabCritical.setFrameShape(QtWidgets.QFrame.Panel)
        self.tabCritical.setObjectName("tabCritical")
        self.tabCritical.setColumnCount(0)
        self.tabCritical.setRowCount(0)
        self.label_3 = QtWidgets.QLabel(criticalItems)
        self.label_3.setGeometry(QtCore.QRect(20, 20, 761, 51))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: black;")
        self.label_3.setLineWidth(1)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.btnClose = QtWidgets.QPushButton(criticalItems)
        self.btnClose.setGeometry(QtCore.QRect(340, 350, 125, 35))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.btnClose.setFont(font)
        self.btnClose.setStyleSheet("QPushButton{\n"
"    background: #365b6d;\n"
"    color: white;\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius:10px;\n"
"    border-color: black;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #53786d;\n"
"    border: 2px solid black;\n"
"}\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background-color: #365b6d;\n"
"}")
        self.btnClose.setObjectName("btnClose")

        self.retranslateUi(criticalItems)
        QtCore.QMetaObject.connectSlotsByName(criticalItems)

    def retranslateUi(self, criticalItems):
        _translate = QtCore.QCoreApplication.translate
        criticalItems.setWindowTitle(_translate("criticalItems", "Critical items"))
        self.label_3.setText(_translate("criticalItems", "Critical Items"))
        self.btnClose.setText(_translate("criticalItems", "Close"))
