# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Joumongo\Documents\Economystique2.0\dashboard.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dashboard(object):
    def setupUi(self, Dashboard):
        Dashboard.setObjectName("Dashboard")
        Dashboard.resize(1600, 900)
        Dashboard.setStyleSheet("color: black;\n"
"background: #E8E6E6;")
        self.frame = QtWidgets.QFrame(Dashboard)
        self.frame.setGeometry(QtCore.QRect(0, 0, 1601, 61))
        self.frame.setStyleSheet("background: #F6f2f2;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.btnObs = QtWidgets.QPushButton(self.frame)
        self.btnObs.setGeometry(QtCore.QRect(0, 0, 321, 61))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(22)
        self.btnObs.setFont(font)
        self.btnObs.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnObs.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    color: #587c6c;\n"
"    border-radius: 50px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #e9e8e7;\n"
"}\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background-color: #e9e8e7;\n"
"}\n"
"")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("c:\\Users\\Joumongo\\Documents\\Economystique2.0\\img/econologo_transparent_cropped.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnObs.setIcon(icon)
        self.btnObs.setIconSize(QtCore.QSize(30, 30))
        self.btnObs.setObjectName("btnObs")
        self.btnNotif = QtWidgets.QPushButton(self.frame)
        self.btnNotif.setGeometry(QtCore.QRect(1510, 10, 51, 41))
        self.btnNotif.setStyleSheet("QPushButton {\n"
"    background: rgba(98,91,113,0.25);\n"
"    border: 0px;\n"
"border-radius: 20px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: rgba(98,91,113,0.15);\n"
"}")
        self.btnNotif.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("c:\\Users\\Joumongo\\Documents\\Economystique2.0\\img/notification-bell.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnNotif.setIcon(icon1)
        self.btnNotif.setIconSize(QtCore.QSize(20, 20))
        self.btnNotif.setObjectName("btnNotif")
        self.lblBadge = QtWidgets.QLabel(self.frame)
        self.lblBadge.setGeometry(QtCore.QRect(1540, 30, 20, 20))
        self.lblBadge.setStyleSheet("color: white;\n"
"background-color: red;\n"
"border-radius: 10px;\n"
"border: 1px solid #706c6c;")
        self.lblBadge.setAlignment(QtCore.Qt.AlignCenter)
        self.lblBadge.setWordWrap(True)
        self.lblBadge.setObjectName("lblBadge")
        self.lsExpProducts = QtWidgets.QListWidget(Dashboard)
        self.lsExpProducts.setGeometry(QtCore.QRect(1170, 60, 411, 91))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.lsExpProducts.setFont(font)
        self.lsExpProducts.setStyleSheet("border-right: 1px solid #706c6c;\n"
"border-left: 1px solid #706c6c;\n"
"border-bottom: 1px solid #706c6c;\n"
"border-bottom-left-radius: 10px;\n"
"border-bottom-right-radius: 10px;\n"
"background-color: #F6f2f2;\n"
"color: black;\n"
"margin-left: 5px;\n"
"margin-right: 5px;")
        self.lsExpProducts.setObjectName("lsExpProducts")
        self.frame_3 = QtWidgets.QFrame(Dashboard)
        self.frame_3.setGeometry(QtCore.QRect(0, 60, 261, 841))
        self.frame_3.setStyleSheet("background: #F6F2F2;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.frame_3)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 120, 261, 231))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Gadugi")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("margin-left: 5px;")
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.btnIngredients = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnIngredients.sizePolicy().hasHeightForWidth())
        self.btnIngredients.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnIngredients.setFont(font)
        self.btnIngredients.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnIngredients.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    color: black;\n"
"    border-radius: 50px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #e9e8e7;\n"
"}\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background-color: #e9e8e7;\n"
"}\n"
"")
        self.btnIngredients.setCheckable(False)
        self.btnIngredients.setObjectName("btnIngredients")
        self.verticalLayout.addWidget(self.btnIngredients)
        self.btnProducts = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnProducts.sizePolicy().hasHeightForWidth())
        self.btnProducts.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnProducts.setFont(font)
        self.btnProducts.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnProducts.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    color: black;\n"
"    border-radius: 50px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #e9e8e7;\n"
"}\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background-color: #e9e8e7;\n"
"}\n"
"")
        self.btnProducts.setCheckable(False)
        self.btnProducts.setObjectName("btnProducts")
        self.verticalLayout.addWidget(self.btnProducts)
        self.btnCritical = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnCritical.sizePolicy().hasHeightForWidth())
        self.btnCritical.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnCritical.setFont(font)
        self.btnCritical.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnCritical.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    color: black;\n"
"    border-radius: 50px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #e9e8e7;\n"
"}\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background-color: #e9e8e7;\n"
"}\n"
"")
        self.btnCritical.setCheckable(False)
        self.btnCritical.setObjectName("btnCritical")
        self.verticalLayout.addWidget(self.btnCritical)
        self.btnWastage = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnWastage.sizePolicy().hasHeightForWidth())
        self.btnWastage.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnWastage.setFont(font)
        self.btnWastage.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnWastage.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    color: black;\n"
"    border-radius: 50px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #e9e8e7;\n"
"}\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background-color: #e9e8e7;\n"
"}\n"
"")
        self.btnWastage.setIconSize(QtCore.QSize(50, 50))
        self.btnWastage.setCheckable(False)
        self.btnWastage.setObjectName("btnWastage")
        self.verticalLayout.addWidget(self.btnWastage)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.frame_3)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(0, 350, 261, 121))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Gadugi")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("margin-left: 5px;")
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.btnSales = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnSales.sizePolicy().hasHeightForWidth())
        self.btnSales.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnSales.setFont(font)
        self.btnSales.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnSales.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    color: black;\n"
"    border-radius: 50px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #e9e8e7;\n"
"}\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background-color: #e9e8e7;\n"
"}\n"
"")
        self.btnSales.setCheckable(False)
        self.btnSales.setObjectName("btnSales")
        self.verticalLayout_2.addWidget(self.btnSales)
        self.btnPOS = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnPOS.sizePolicy().hasHeightForWidth())
        self.btnPOS.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnPOS.setFont(font)
        self.btnPOS.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnPOS.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    color: black;\n"
"    border-radius: 50px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #e9e8e7;\n"
"}\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background-color: #e9e8e7;\n"
"}\n"
"")
        self.btnPOS.setCheckable(False)
        self.btnPOS.setObjectName("btnPOS")
        self.verticalLayout_2.addWidget(self.btnPOS)
        self.btnAccount = QtWidgets.QPushButton(self.frame_3)
        self.btnAccount.setGeometry(QtCore.QRect(0, 760, 261, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnAccount.sizePolicy().hasHeightForWidth())
        self.btnAccount.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnAccount.setFont(font)
        self.btnAccount.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnAccount.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    color: black;\n"
"    border-radius: 50px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #e9e8e7;\n"
"}\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background-color: #e9e8e7;\n"
"}\n"
"")
        self.btnAccount.setObjectName("btnAccount")
        self.btnLogOut = QtWidgets.QPushButton(self.frame_3)
        self.btnLogOut.setGeometry(QtCore.QRect(0, 800, 261, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnLogOut.sizePolicy().hasHeightForWidth())
        self.btnLogOut.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnLogOut.setFont(font)
        self.btnLogOut.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnLogOut.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    color: black;\n"
"    border-radius: 50px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #e9e8e7;\n"
"}\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background-color: #e9e8e7;\n"
"}\n"
"")
        self.btnLogOut.setObjectName("btnLogOut")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.frame_3)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(0, 0, 261, 121))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_13 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Gadugi")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("margin-left: 5px;")
        self.label_13.setObjectName("label_13")
        self.verticalLayout_3.addWidget(self.label_13)
        self.btnDashboard = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnDashboard.sizePolicy().hasHeightForWidth())
        self.btnDashboard.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnDashboard.setFont(font)
        self.btnDashboard.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnDashboard.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    color: black;\n"
"    border-radius: 50px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #e9e8e7;\n"
"}\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background-color: #e9e8e7;\n"
"}\n"
"")
        self.btnDashboard.setCheckable(False)
        self.btnDashboard.setObjectName("btnDashboard")
        self.verticalLayout_3.addWidget(self.btnDashboard)
        self.btnCompare_2 = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnCompare_2.sizePolicy().hasHeightForWidth())
        self.btnCompare_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnCompare_2.setFont(font)
        self.btnCompare_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnCompare_2.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    color: black;\n"
"    border-radius: 50px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #e9e8e7;\n"
"}\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background-color: #e9e8e7;\n"
"}\n"
"")
        self.btnCompare_2.setCheckable(False)
        self.btnCompare_2.setObjectName("btnCompare_2")
        self.verticalLayout_3.addWidget(self.btnCompare_2)
        self.lblWelcomeName = QtWidgets.QLabel(Dashboard)
        self.lblWelcomeName.setGeometry(QtCore.QRect(290, 70, 671, 81))
        font = QtGui.QFont()
        font.setFamily("Gadugi")
        font.setPointSize(22)
        self.lblWelcomeName.setFont(font)
        self.lblWelcomeName.setStyleSheet("background: transparent;")
        self.lblWelcomeName.setObjectName("lblWelcomeName")
        self.horizontalLayoutWidget = QtWidgets.QWidget(Dashboard)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(280, 150, 891, 301))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_2 = QtWidgets.QFrame(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setStyleSheet("#frame_2{\n"
"    border-radius: 10px;\n"
"    background: white;\n"
"    margin: 5px;\n"
"    border: 1px solid #706c6c;\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.lblBestProduct = QtWidgets.QLabel(self.frame_2)
        self.lblBestProduct.setGeometry(QtCore.QRect(20, 60, 401, 191))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lblBestProduct.setFont(font)
        self.lblBestProduct.setStyleSheet("border-top-right-radius: 5px;\n"
"border-top-left-radius: 5px;\n"
"background: transparent;\n"
"color: black;")
        self.lblBestProduct.setText("")
        self.lblBestProduct.setAlignment(QtCore.Qt.AlignCenter)
        self.lblBestProduct.setWordWrap(True)
        self.lblBestProduct.setObjectName("lblBestProduct")
        self.frame_8 = QtWidgets.QFrame(self.frame_2)
        self.frame_8.setGeometry(QtCore.QRect(0, 0, 445, 51))
        self.frame_8.setStyleSheet("#frame_8{\n"
"    border: 1px solid #706c6c;\n"
"    border-top-left-radius: 10px;\n"
"    border-top-right-radius: 10px;\n"
"    background: #DDA853;\n"
"    margin: 5px;\n"
"}")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame_8)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_4 = QtWidgets.QLabel(self.frame_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Gadugi")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("background: transparent;\n"
"color: white;\n"
"margin-left: 5px;")
        self.label_4.setLineWidth(1)
        self.label_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_5.addWidget(self.label_4, 0, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.frame_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setMinimumSize(QtCore.QSize(50, 0))
        self.label_6.setStyleSheet("background: transparent;\n"
"color: white;")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_5.addWidget(self.label_6, 0, 0, 1, 1)
        self.horizontalLayout.addWidget(self.frame_2)
        self.frame_4 = QtWidgets.QFrame(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        self.frame_4.setStyleSheet("#frame_4{\n"
"    border-radius: 10px;\n"
"    background: white;\n"
"    margin: 5px;\n"
"    border: 1px solid #706c6c;\n"
"}")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.frame_9 = QtWidgets.QFrame(self.frame_4)
        self.frame_9.setGeometry(QtCore.QRect(0, 0, 444, 51))
        self.frame_9.setStyleSheet("#frame_9{\n"
"    border: 1px solid #706c6c;\n"
"    border-top-left-radius: 10px;\n"
"    border-top-right-radius: 10px;\n"
"    background: #215E7D;\n"
"    margin: 5px;\n"
"}")
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_9)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_7 = QtWidgets.QLabel(self.frame_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Gadugi")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("background: transparent;\n"
"color: white;\n"
"margin-left: 5px;")
        self.label_7.setLineWidth(1)
        self.label_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_4.addWidget(self.label_7, 0, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.frame_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setMinimumSize(QtCore.QSize(50, 0))
        self.label_9.setStyleSheet("background: transparent;\n"
"color: white;")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_4.addWidget(self.label_9, 0, 0, 1, 1)
        self.horizontalLayout.addWidget(self.frame_4)
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(Dashboard)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(1170, 150, 411, 741))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_6 = QtWidgets.QFrame(self.verticalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_6.sizePolicy().hasHeightForWidth())
        self.frame_6.setSizePolicy(sizePolicy)
        self.frame_6.setStyleSheet("#frame_6{\n"
"    border-radius: 10px;\n"
"    background: white;\n"
"    margin: 5px;\n"
"    border: 1px solid #706c6c;\n"
"}\n"
"")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.frame_10 = QtWidgets.QFrame(self.frame_6)
        self.frame_10.setGeometry(QtCore.QRect(0, 0, 409, 51))
        self.frame_10.setStyleSheet("#frame_10{\n"
"    border: 1px solid #706c6c;\n"
"    border-top-left-radius: 10px;\n"
"    border-top-right-radius: 10px;\n"
"    background: #B03052;\n"
"    margin: 5px;\n"
"}")
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_10)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_8 = QtWidgets.QLabel(self.frame_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Gadugi")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("background: transparent;\n"
"color: white;\n"
"margin-left: 5px;")
        self.label_8.setLineWidth(1)
        self.label_8.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 0, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.frame_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setMinimumSize(QtCore.QSize(50, 0))
        self.label_10.setStyleSheet("background: transparent;\n"
"color: white;")
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 0, 0, 1, 1)
        self.verticalLayout_4.addWidget(self.frame_6)
        self.frame_7 = QtWidgets.QFrame(self.verticalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_7.sizePolicy().hasHeightForWidth())
        self.frame_7.setSizePolicy(sizePolicy)
        self.frame_7.setStyleSheet("#frame_7{\n"
"    border: 1px solid #706c6c;\n"
"    border-radius: 10px;\n"
"    background: white;\n"
"    margin: 5px;\n"
"}\n"
"")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.frame_11 = QtWidgets.QFrame(self.frame_7)
        self.frame_11.setGeometry(QtCore.QRect(0, 0, 409, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_11.sizePolicy().hasHeightForWidth())
        self.frame_11.setSizePolicy(sizePolicy)
        self.frame_11.setStyleSheet("#frame_11{\n"
"border: 1px solid #706c6c;\n"
"border-top-left-radius: 10px;\n"
"border-top-right-radius: 10px;\n"
"background: #B03032;\n"
"margin: 5px;\n"
"}")
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_11)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_11 = QtWidgets.QLabel(self.frame_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setMinimumSize(QtCore.QSize(50, 0))
        self.label_11.setStyleSheet("background: transparent;\n"
"color: white;")
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_3.addWidget(self.label_11)
        self.label = QtWidgets.QLabel(self.frame_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Gadugi")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setStyleSheet("background: transparent;\n"
"color: white;")
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.verticalLayout_4.addWidget(self.frame_7)
        self.gridLayoutWidget = QtWidgets.QWidget(Dashboard)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(280, 450, 891, 441))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame_12 = QtWidgets.QFrame(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_12.sizePolicy().hasHeightForWidth())
        self.frame_12.setSizePolicy(sizePolicy)
        self.frame_12.setStyleSheet("#frame_12{\n"
"    border: 1px solid #706c6c;\n"
"    border-radius: 10px;\n"
"    background: white;\n"
"margin: 5px;\n"
"}")
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.frame_5 = QtWidgets.QFrame(self.frame_12)
        self.frame_5.setGeometry(QtCore.QRect(10, 80, 861, 41))
        self.frame_5.setStyleSheet("QFrame{\n"
"    border-radius: 5px;\n"
"    background: #cfe6ed;\n"
"}\n"
"")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout.setContentsMargins(1, 1, 1, 1)
        self.gridLayout.setObjectName("gridLayout")
        self.lblPerformance = QtWidgets.QLabel(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblPerformance.sizePolicy().hasHeightForWidth())
        self.lblPerformance.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Gadugi")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lblPerformance.setFont(font)
        self.lblPerformance.setStyleSheet("background: transparent;\n"
"color: black;")
        self.lblPerformance.setText("")
        self.lblPerformance.setAlignment(QtCore.Qt.AlignCenter)
        self.lblPerformance.setWordWrap(True)
        self.lblPerformance.setObjectName("lblPerformance")
        self.gridLayout.addWidget(self.lblPerformance, 0, 0, 1, 1)
        self.gpPerformance = QtWidgets.QWidget(self.frame_12)
        self.gpPerformance.setGeometry(QtCore.QRect(10, 120, 861, 311))
        self.gpPerformance.setStyleSheet("QWidget {\n"
"    border-radius: 5px;\n"
"    background-color: transparent;\n"
"    padding: 0px;\n"
"}")
        self.gpPerformance.setObjectName("gpPerformance")
        self.frame_13 = QtWidgets.QFrame(self.frame_12)
        self.frame_13.setGeometry(QtCore.QRect(0, 0, 889, 71))
        self.frame_13.setStyleSheet("#frame_13{\n"
"border: 1px solid #706c6c;\n"
"border-top-left-radius: 5px;\n"
"border-top-right-radius: 5px;\n"
"background: #F6F2F2;\n"
"margin: 5px;\n"
"}")
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.frame_13)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(570, 20, 131, 41))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btnDaily = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnDaily.sizePolicy().hasHeightForWidth())
        self.btnDaily.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.btnDaily.setFont(font)
        self.btnDaily.setStyleSheet("QPushButton{\n"
"    background: #d9d9d9;\n"
"    color: black;\n"
"    border-style: outset;\n"
"    border-radius:10px;\n"
"    border-color: black;\n"
"    margin: 2px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #e9e8e7;\n"
"}\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background-color: #e9e8e7;\n"
"}")
        self.btnDaily.setObjectName("btnDaily")
        self.horizontalLayout_2.addWidget(self.btnDaily)
        self.btnMonthly = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnMonthly.sizePolicy().hasHeightForWidth())
        self.btnMonthly.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.btnMonthly.setFont(font)
        self.btnMonthly.setStyleSheet("QPushButton{\n"
"    background: #d9d9d9;\n"
"    color: black;\n"
"    border-style: outset;\n"
"    border-radius:10px;\n"
"    border-color: black;\n"
"    margin: 2px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #e9e8e7;\n"
"}\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background-color: #e9e8e7;\n"
"}")
        self.btnMonthly.setObjectName("btnMonthly")
        self.horizontalLayout_2.addWidget(self.btnMonthly)
        self.btnYearly = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnYearly.sizePolicy().hasHeightForWidth())
        self.btnYearly.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.btnYearly.setFont(font)
        self.btnYearly.setStyleSheet("QPushButton{\n"
"    background: #d9d9d9;\n"
"    color: black;\n"
"    border-style: outset;\n"
"    border-radius:10px;\n"
"    border-color: black;\n"
"    margin: 2px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #e9e8e7;\n"
"}\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background-color: #e9e8e7;\n"
"}")
        self.btnYearly.setObjectName("btnYearly")
        self.horizontalLayout_2.addWidget(self.btnYearly)
        self.btnCompare = QtWidgets.QPushButton(self.frame_13)
        self.btnCompare.setGeometry(QtCore.QRect(720, 20, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.btnCompare.setFont(font)
        self.btnCompare.setStyleSheet("QPushButton{\n"
"    background: #d9d9d9;\n"
"    color: black;\n"
"    border-style: outset;\n"
"    border-radius:10px;\n"
"    border-color: black;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #e9e8e7;\n"
"}\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background-color: #e9e8e7;\n"
"}")
        self.btnCompare.setObjectName("btnCompare")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.frame_13)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(10, 10, 541, 51))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_12 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setMinimumSize(QtCore.QSize(50, 0))
        self.label_12.setStyleSheet("background: transparent;\n"
"color: black;")
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_4.addWidget(self.label_12)
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Gadugi")
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background: transparent;\n"
"margin-left: 5px;")
        self.label_2.setScaledContents(False)
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.gridLayout_2.addWidget(self.frame_12, 0, 0, 1, 1)

        self.retranslateUi(Dashboard)
        QtCore.QMetaObject.connectSlotsByName(Dashboard)

    def retranslateUi(self, Dashboard):
        _translate = QtCore.QCoreApplication.translate
        Dashboard.setWindowTitle(_translate("Dashboard", "Form"))
        self.btnObs.setText(_translate("Dashboard", "ECONOMYSTIQUE"))
        self.lblBadge.setText(_translate("Dashboard", "2"))
        self.label_3.setText(_translate("Dashboard", "Inventory"))
        self.btnIngredients.setText(_translate("Dashboard", "Ingredients"))
        self.btnProducts.setText(_translate("Dashboard", "Products"))
        self.btnCritical.setText(_translate("Dashboard", "Low Stocks"))
        self.btnWastage.setText(_translate("Dashboard", "Wastage"))
        self.label_5.setText(_translate("Dashboard", "Sales"))
        self.btnSales.setText(_translate("Dashboard", "Sales"))
        self.btnPOS.setText(_translate("Dashboard", "POS"))
        self.btnAccount.setText(_translate("Dashboard", "Profile"))
        self.btnLogOut.setText(_translate("Dashboard", "Logout"))
        self.label_13.setText(_translate("Dashboard", "Home"))
        self.btnDashboard.setText(_translate("Dashboard", "Dashboard"))
        self.btnCompare_2.setText(_translate("Dashboard", "Compare Performance"))
        self.lblWelcomeName.setText(_translate("Dashboard", "Welcome, Admin!"))
        self.label_4.setText(_translate("Dashboard", "Top Products"))
        self.label_6.setText(_translate("Dashboard", "Icon"))
        self.label_7.setText(_translate("Dashboard", "Least Sold Products"))
        self.label_9.setText(_translate("Dashboard", "Icon"))
        self.label_8.setText(_translate("Dashboard", "Near Expiry Products"))
        self.label_10.setText(_translate("Dashboard", "Icon"))
        self.label_11.setText(_translate("Dashboard", "Icon"))
        self.label.setText(_translate("Dashboard", "Critical Items"))
        self.btnDaily.setToolTip(_translate("Dashboard", "Daily"))
        self.btnDaily.setText(_translate("Dashboard", "D"))
        self.btnMonthly.setToolTip(_translate("Dashboard", "Monthly"))
        self.btnMonthly.setText(_translate("Dashboard", "M"))
        self.btnYearly.setToolTip(_translate("Dashboard", "Yearly"))
        self.btnYearly.setText(_translate("Dashboard", "Y"))
        self.btnCompare.setText(_translate("Dashboard", "COMPARE"))
        self.label_12.setText(_translate("Dashboard", "Icon"))
        self.label_2.setText(_translate("Dashboard", "Performance"))
