# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Joumongo\Documents\Economystique\restock.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Restock(object):
    def setupUi(self, Restock):
        Restock.setObjectName("Restock")
        Restock.resize(1000, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("c:\\Users\\Joumongo\\Documents\\Economystique\\img/econologo_bkgd 200.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Restock.setWindowIcon(icon)
        Restock.setStyleSheet("background-color: #f4f4ec;")
        self.btnConfirm = QtWidgets.QPushButton(Restock)
        self.btnConfirm.setGeometry(QtCore.QRect(350, 530, 125, 35))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.btnConfirm.setFont(font)
        self.btnConfirm.setStyleSheet("QPushButton{\n"
"    background: #365b6d;\n"
"    color: white;\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius:10px;\n"
"    border-color: black;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #53786d;\n"
"    border: 2px solid black;\n"
"}\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background-color: #365b6d;\n"
"}")
        self.btnConfirm.setObjectName("btnConfirm")
        self.btnCancel = QtWidgets.QPushButton(Restock)
        self.btnCancel.setGeometry(QtCore.QRect(500, 530, 125, 35))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.btnCancel.setFont(font)
        self.btnCancel.setStyleSheet("QPushButton{\n"
"    background: #365b6d;\n"
"    color: white;\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius:10px;\n"
"    border-color: black;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #53786d;\n"
"    border: 2px solid black;\n"
"}\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background-color: #365b6d;\n"
"}")
        self.btnCancel.setObjectName("btnCancel")
        self.label_9 = QtWidgets.QLabel(Restock)
        self.label_9.setGeometry(QtCore.QRect(20, 10, 961, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.btnRemove = QtWidgets.QPushButton(Restock)
        self.btnRemove.setGeometry(QtCore.QRect(780, 360, 200, 50))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.btnRemove.setFont(font)
        self.btnRemove.setStyleSheet("QPushButton{\n"
"    background: #365b6d;\n"
"    color: white;\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius:10px;\n"
"    border-color: black;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #53786d;\n"
"    border: 2px solid black;\n"
"}\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background-color: #365b6d;\n"
"}")
        self.btnRemove.setObjectName("btnRemove")
        self.btnAddNew = QtWidgets.QPushButton(Restock)
        self.btnAddNew.setGeometry(QtCore.QRect(780, 270, 200, 50))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.btnAddNew.setFont(font)
        self.btnAddNew.setStyleSheet("QPushButton{\n"
"    background: #365b6d;\n"
"    color: white;\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius:10px;\n"
"    border-color: black;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #53786d;\n"
"    border: 2px solid black;\n"
"}\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background-color: #365b6d;\n"
"}")
        self.btnAddNew.setObjectName("btnAddNew")
        self.tabRestockTable = QtWidgets.QTableWidget(Restock)
        self.tabRestockTable.setGeometry(QtCore.QRect(20, 80, 741, 421))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabRestockTable.sizePolicy().hasHeightForWidth())
        self.tabRestockTable.setSizePolicy(sizePolicy)
        self.tabRestockTable.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        self.tabRestockTable.setFont(font)
        self.tabRestockTable.setStyleSheet("background: #ffffff")
        self.tabRestockTable.setFrameShape(QtWidgets.QFrame.Panel)
        self.tabRestockTable.setObjectName("tabRestockTable")
        self.tabRestockTable.setColumnCount(0)
        self.tabRestockTable.setRowCount(0)
        self.btnAdd = QtWidgets.QPushButton(Restock)
        self.btnAdd.setGeometry(QtCore.QRect(780, 180, 200, 50))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.btnAdd.setFont(font)
        self.btnAdd.setStyleSheet("QPushButton{\n"
"    background: #365b6d;\n"
"    color: white;\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius:10px;\n"
"    border-color: black;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #53786d;\n"
"    border: 2px solid black;\n"
"}\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background-color: #365b6d;\n"
"}")
        self.btnAdd.setObjectName("btnAdd")

        self.retranslateUi(Restock)
        QtCore.QMetaObject.connectSlotsByName(Restock)

    def retranslateUi(self, Restock):
        _translate = QtCore.QCoreApplication.translate
        Restock.setWindowTitle(_translate("Restock", "Restock Inventory"))
        self.btnConfirm.setText(_translate("Restock", "✔️ Confirm"))
        self.btnCancel.setText(_translate("Restock", "❌ Cancel"))
        self.label_9.setText(_translate("Restock", "Restock Inventory"))
        self.btnRemove.setText(_translate("Restock", "Remove"))
        self.btnAddNew.setText(_translate("Restock", "Add New Item"))
        self.btnAdd.setText(_translate("Restock", "Add Existing Item"))
