# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Joumongo\Documents\Economystique\sales.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Sales(object):
    def setupUi(self, Sales):
        Sales.setObjectName("Sales")
        Sales.resize(1600, 900)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("c:\\Users\\Joumongo\\Documents\\Economystique\\../.designer/backup/img/econoLogo2.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        Sales.setWindowIcon(icon)
        Sales.setStyleSheet("color: black;")
        self.SalesRecords = QtWidgets.QLabel(Sales)
        self.SalesRecords.setGeometry(QtCore.QRect(650, 30, 311, 91))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(22)
        self.SalesRecords.setFont(font)
        self.SalesRecords.setStyleSheet("border: 0px solid white;\n"
"background: #365b6d;\n"
"color: white;\n"
"border-radius: 25px;")
        self.SalesRecords.setAlignment(QtCore.Qt.AlignCenter)
        self.SalesRecords.setObjectName("SalesRecords")
        self.QTabWidget = QtWidgets.QTabWidget(Sales)
        self.QTabWidget.setGeometry(QtCore.QRect(20, 130, 1561, 741))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(20)
        self.QTabWidget.setFont(font)
        self.QTabWidget.setStyleSheet("QTabWidget::pane {\n"
"    border: 1px solid white;\n"
"    border-top-right-radius: 10px;\n"
"    border-bottom-left-radius: 10px;\n"
"    border-bottom-right-radius: 10px;\n"
"    background-color: rgba(255,255,255,164);\n"
"}\n"
"QTabBar::tab {\n"
"    background: #365b6d;\n"
"    border: 1px solid white;\n"
"    padding: 8px;\n"
"    border-top-left-radius: 10px;\n"
"    border-top-right-radius: 10px;\n"
"    min-width: 100px;\n"
"    color: white;\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"    background: #53786d;\n"
"    color: white;\n"
"}\n"
"\n"
"QTabBar::tab:hover {\n"
"    background: #53786d;\n"
"}")
        self.QTabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.QTabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.QTabWidget.setObjectName("QTabWidget")
        self.tabToday = QtWidgets.QWidget()
        self.tabToday.setObjectName("tabToday")
        self.productTable = QtWidgets.QTableWidget(self.tabToday)
        self.productTable.setGeometry(QtCore.QRect(0, 90, 1561, 481))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.productTable.setFont(font)
        self.productTable.setStyleSheet("QTableWidget {\n"
"        background-color: rgba(255, 255, 255, 50);\n"
"        selection-background-color: #087cd4;\n"
"        selection-color: white;\n"
"        border: none;\n"
"    }\n"
"    QHeaderView::section {\n"
"        background-color: rgba(255, 255, 255, 50);\n"
"    }\n"
"    QTableWidget::item {\n"
"        background-color: rgba(255, 255, 255, 50);\n"
"    }\n"
"QTableWidget::item:selected { \n"
"        background-color: #087cd4;\n"
"        color: white;\n"
"    }")
        self.productTable.setFrameShape(QtWidgets.QFrame.Panel)
        self.productTable.setObjectName("productTable")
        self.productTable.setColumnCount(0)
        self.productTable.setRowCount(0)
        self.lblTotal = QtWidgets.QLabel(self.tabToday)
        self.lblTotal.setGeometry(QtCore.QRect(620, 600, 301, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lblTotal.setFont(font)
        self.lblTotal.setStyleSheet("background: white;\n"
"")
        self.lblTotal.setFrameShape(QtWidgets.QFrame.Box)
        self.lblTotal.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lblTotal.setText("")
        self.lblTotal.setAlignment(QtCore.Qt.AlignCenter)
        self.lblTotal.setObjectName("lblTotal")
        self.label = QtWidgets.QLabel(self.tabToday)
        self.label.setGeometry(QtCore.QRect(520, 600, 81, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setStyleSheet("")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.btnForecast = QtWidgets.QPushButton(self.tabToday)
        self.btnForecast.setGeometry(QtCore.QRect(1110, 590, 291, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btnForecast.setFont(font)
        self.btnForecast.setStyleSheet("QPushButton{\n"
"    background: #365b6d;\n"
"    color: white;\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius:10px;\n"
"    border-color: black;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #53786d;\n"
"    border: 2px solid black;\n"
"}\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background-color: #365b6d;\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("c:\\Users\\Joumongo\\Documents\\Economystique\\img/econologo_transparent_cropped.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnForecast.setIcon(icon1)
        self.btnForecast.setIconSize(QtCore.QSize(15, 40))
        self.btnForecast.setObjectName("btnForecast")
        self.QTabWidget.addTab(self.tabToday, "")
        self.tabMonthly = QtWidgets.QWidget()
        self.tabMonthly.setObjectName("tabMonthly")
        self.cbMonth = QtWidgets.QComboBox(self.tabMonthly)
        self.cbMonth.setGeometry(QtCore.QRect(160, 30, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cbMonth.setFont(font)
        self.cbMonth.setStyleSheet("background: white;")
        self.cbMonth.setObjectName("cbMonth")
        self.label_3 = QtWidgets.QLabel(self.tabMonthly)
        self.label_3.setGeometry(QtCore.QRect(30, 30, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.tabMonthly)
        self.label_4.setGeometry(QtCore.QRect(520, 600, 81, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.lblMTotal = QtWidgets.QLabel(self.tabMonthly)
        self.lblMTotal.setGeometry(QtCore.QRect(620, 600, 301, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lblMTotal.setFont(font)
        self.lblMTotal.setStyleSheet("background: white;\n"
"")
        self.lblMTotal.setFrameShape(QtWidgets.QFrame.Box)
        self.lblMTotal.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lblMTotal.setText("")
        self.lblMTotal.setAlignment(QtCore.Qt.AlignCenter)
        self.lblMTotal.setObjectName("lblMTotal")
        self.mProductTable = QtWidgets.QTableWidget(self.tabMonthly)
        self.mProductTable.setGeometry(QtCore.QRect(0, 90, 1561, 481))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.mProductTable.setFont(font)
        self.mProductTable.setStyleSheet("QTableWidget {\n"
"        background-color: rgba(255, 255, 255, 50);\n"
"        selection-background-color: #087cd4;\n"
"        selection-color: white;\n"
"        border: none;\n"
"    }\n"
"    QHeaderView::section {\n"
"        background-color: rgba(255, 255, 255, 50);\n"
"    }\n"
"    QTableWidget::item {\n"
"        background-color: rgba(255, 255, 255, 50);\n"
"    }\n"
"QTableWidget::item:selected { \n"
"        background-color: #087cd4;\n"
"        color: white;\n"
"    }")
        self.mProductTable.setFrameShape(QtWidgets.QFrame.Panel)
        self.mProductTable.setObjectName("mProductTable")
        self.mProductTable.setColumnCount(0)
        self.mProductTable.setRowCount(0)
        self.cbMYear = QtWidgets.QComboBox(self.tabMonthly)
        self.cbMYear.setGeometry(QtCore.QRect(670, 30, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cbMYear.setFont(font)
        self.cbMYear.setStyleSheet("background: white;")
        self.cbMYear.setObjectName("cbMYear")
        self.label_7 = QtWidgets.QLabel(self.tabMonthly)
        self.label_7.setGeometry(QtCore.QRect(540, 30, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(16)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.QTabWidget.addTab(self.tabMonthly, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.cbYear = QtWidgets.QComboBox(self.tab)
        self.cbYear.setGeometry(QtCore.QRect(670, 30, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cbYear.setFont(font)
        self.cbYear.setStyleSheet("background: white;")
        self.cbYear.setObjectName("cbYear")
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setGeometry(QtCore.QRect(540, 30, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(16)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.yProductTable = QtWidgets.QTableWidget(self.tab)
        self.yProductTable.setGeometry(QtCore.QRect(0, 90, 1561, 481))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.yProductTable.setFont(font)
        self.yProductTable.setStyleSheet("QTableWidget {\n"
"        background-color: rgba(255, 255, 255, 50);\n"
"        selection-background-color: #087cd4;\n"
"        selection-color: white;\n"
"        border: none;\n"
"    }\n"
"    QHeaderView::section {\n"
"        background-color: rgba(255, 255, 255, 50);\n"
"    }\n"
"    QTableWidget::item {\n"
"        background-color: rgba(255, 255, 255, 50);\n"
"    }\n"
"QTableWidget::item:selected { \n"
"        background-color: #087cd4;\n"
"        color: white;\n"
"    }")
        self.yProductTable.setFrameShape(QtWidgets.QFrame.Panel)
        self.yProductTable.setObjectName("yProductTable")
        self.yProductTable.setColumnCount(0)
        self.yProductTable.setRowCount(0)
        self.lblYTotal = QtWidgets.QLabel(self.tab)
        self.lblYTotal.setGeometry(QtCore.QRect(620, 600, 301, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lblYTotal.setFont(font)
        self.lblYTotal.setStyleSheet("background: white;\n"
"")
        self.lblYTotal.setFrameShape(QtWidgets.QFrame.Box)
        self.lblYTotal.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lblYTotal.setText("")
        self.lblYTotal.setAlignment(QtCore.Qt.AlignCenter)
        self.lblYTotal.setObjectName("lblYTotal")
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setGeometry(QtCore.QRect(520, 600, 81, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.QTabWidget.addTab(self.tab, "")
        self.frame = QtWidgets.QFrame(Sales)
        self.frame.setGeometry(QtCore.QRect(0, 0, 1601, 61))
        self.frame.setStyleSheet("background: #365b6d;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.btnSales = QtWidgets.QPushButton(self.frame)
        self.btnSales.setGeometry(QtCore.QRect(1312, 0, 111, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnSales.setFont(font)
        self.btnSales.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnSales.setStyleSheet("QPushButton {\n"
"    background-color: #365b6d;\n"
"    color: white;\n"
"    border-radius: 50px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #5b8ca4;\n"
"}\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background-color: #365b6d;\n"
"}\n"
"")
        self.btnSales.setObjectName("btnSales")
        self.btnInventory = QtWidgets.QPushButton(self.frame)
        self.btnInventory.setGeometry(QtCore.QRect(1202, 0, 111, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnInventory.setFont(font)
        self.btnInventory.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnInventory.setStyleSheet("QPushButton {\n"
"    background-color: #365b6d;\n"
"    color: white;\n"
"    border-radius: 50px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #5b8ca4;\n"
"}\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background-color: #365b6d;\n"
"}\n"
"")
        self.btnInventory.setObjectName("btnInventory")
        self.btnPOS = QtWidgets.QPushButton(self.frame)
        self.btnPOS.setGeometry(QtCore.QRect(1422, 0, 111, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnPOS.setFont(font)
        self.btnPOS.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnPOS.setStyleSheet("QPushButton {\n"
"    background-color: #365b6d;\n"
"    color: white;\n"
"    border-radius: 50px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #5b8ca4;\n"
"}\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background-color: #365b6d;\n"
"}\n"
"")
        self.btnPOS.setObjectName("btnPOS")
        self.btnAccount = QtWidgets.QPushButton(self.frame)
        self.btnAccount.setGeometry(QtCore.QRect(1530, 0, 71, 61))
        self.btnAccount.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnAccount.setStyleSheet("QPushButton {\n"
"    background-color: #365b6d;\n"
"    color: white;\n"
"    border-radius: 50px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #5b8ca4;\n"
"}\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background-color: #365b6d;\n"
"}\n"
"")
        self.btnAccount.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("c:\\Users\\Joumongo\\Documents\\Economystique\\img/pfBtn.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        self.btnAccount.setIcon(icon2)
        self.btnAccount.setIconSize(QtCore.QSize(50, 50))
        self.btnAccount.setObjectName("btnAccount")
        self.btnDashboard = QtWidgets.QPushButton(self.frame)
        self.btnDashboard.setGeometry(QtCore.QRect(0, 0, 291, 61))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(22)
        self.btnDashboard.setFont(font)
        self.btnDashboard.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnDashboard.setStyleSheet("QPushButton {\n"
"    background-color: #365b6d;\n"
"    color: white;\n"
"    border-radius: 50px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #5b8ca4;\n"
"}\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background-color: #365b6d;\n"
"}\n"
"")
        self.btnDashboard.setIcon(icon1)
        self.btnDashboard.setIconSize(QtCore.QSize(30, 30))
        self.btnDashboard.setObjectName("btnDashboard")

        self.retranslateUi(Sales)
        self.QTabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Sales)

    def retranslateUi(self, Sales):
        _translate = QtCore.QCoreApplication.translate
        Sales.setWindowTitle(_translate("Sales", "EconoMystique"))
        self.SalesRecords.setText(_translate("Sales", "Sales"))
        self.label.setText(_translate("Sales", "Total"))
        self.btnForecast.setText(_translate("Sales", "Generate Forecast"))
        self.QTabWidget.setTabText(self.QTabWidget.indexOf(self.tabToday), _translate("Sales", "Today"))
        self.label_3.setText(_translate("Sales", "Month:"))
        self.label_4.setText(_translate("Sales", "Total"))
        self.label_7.setText(_translate("Sales", "Year:"))
        self.QTabWidget.setTabText(self.QTabWidget.indexOf(self.tabMonthly), _translate("Sales", "Monthly"))
        self.label_5.setText(_translate("Sales", "Year:"))
        self.label_6.setText(_translate("Sales", "Total"))
        self.QTabWidget.setTabText(self.QTabWidget.indexOf(self.tab), _translate("Sales", "Yearly"))
        self.btnSales.setText(_translate("Sales", "Sales"))
        self.btnInventory.setText(_translate("Sales", "Inventory"))
        self.btnPOS.setText(_translate("Sales", "POS"))
        self.btnDashboard.setText(_translate("Sales", "EconoMystique"))
