# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Joumongo\Documents\Economystique\signIn.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_signUp(object):
    def setupUi(self, signUp):
        signUp.setObjectName("signUp")
        signUp.resize(800, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("c:\\Users\\Joumongo\\Documents\\Economystique\\img/econologo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        signUp.setWindowIcon(icon)
        signUp.setStyleSheet("background-color: #f4f4ec;\n"
"color: black;")
        self.usernameLine = QtWidgets.QLineEdit(signUp)
        self.usernameLine.setGeometry(QtCore.QRect(40, 240, 311, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.usernameLine.setFont(font)
        self.usernameLine.setAutoFillBackground(False)
        self.usernameLine.setStyleSheet("color: black;\n"
"background-color: white;")
        self.usernameLine.setText("")
        self.usernameLine.setObjectName("usernameLine")
        self.passwordLine = QtWidgets.QLineEdit(signUp)
        self.passwordLine.setGeometry(QtCore.QRect(40, 340, 311, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.passwordLine.setFont(font)
        self.passwordLine.setStyleSheet("color: black;\n"
"background-color: white;")
        self.passwordLine.setText("")
        self.passwordLine.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordLine.setObjectName("passwordLine")
        self.pushButton = QtWidgets.QPushButton(signUp)
        self.pushButton.setGeometry(QtCore.QRect(40, 400, 311, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(54, 91, 109))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(54, 91, 109))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(54, 91, 109))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(54, 91, 109))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(54, 91, 109))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(54, 91, 109))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(54, 91, 109))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(54, 91, 109))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(54, 91, 109))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.pushButton.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton.setFont(font)
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setStyleSheet("QPushButton {\n"
"    background-color: #365b6d;\n"
"    color: white;\n"
"    border: 2px solid #365b6d;\n"
"    border-radius: 50px;\n"
"    padding: 5px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #289dd2;\n"
"    border: 2px solid #289dd2;\n"
"}\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background-color: #365b6d;\n"
"}\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.usernameLabel = QtWidgets.QLabel(signUp)
        self.usernameLabel.setGeometry(QtCore.QRect(40, 210, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.usernameLabel.setFont(font)
        self.usernameLabel.setObjectName("usernameLabel")
        self.loginButton = QtWidgets.QPushButton(signUp)
        self.loginButton.setGeometry(QtCore.QRect(200, 480, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.loginButton.setFont(font)
        self.loginButton.setStyleSheet("QPushButton {\n"
"    background-color: #53786d;\n"
"    color: white;\n"
"    border: 2px solid #53786d;\n"
"    border-radius: 50px;\n"
"    padding: 5px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #289dd2;\n"
"    border: 2px solid #289dd2;\n"
"}\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background-color: #53786d;\n"
"}\n"
"")
        self.loginButton.setObjectName("loginButton")
        self.loginLabel = QtWidgets.QLabel(signUp)
        self.loginLabel.setGeometry(QtCore.QRect(110, 50, 191, 51))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.loginLabel.setFont(font)
        self.loginLabel.setStyleSheet("color: #365b6d;")
        self.loginLabel.setObjectName("loginLabel")
        self.frame = QtWidgets.QFrame(signUp)
        self.frame.setGeometry(QtCore.QRect(400, 0, 401, 601))
        self.frame.setStyleSheet("background: #365b6d;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(-50, 80, 491, 391))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("c:\\Users\\Joumongo\\Documents\\Economystique\\img/econologo.png"))
        self.label.setObjectName("label")
        self.emailLine = QtWidgets.QLineEdit(signUp)
        self.emailLine.setGeometry(QtCore.QRect(40, 150, 311, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.emailLine.setFont(font)
        self.emailLine.setAutoFillBackground(False)
        self.emailLine.setStyleSheet("color: black;\n"
"background-color: white;")
        self.emailLine.setText("")
        self.emailLine.setObjectName("emailLine")
        self.passwordLabel = QtWidgets.QLabel(signUp)
        self.passwordLabel.setGeometry(QtCore.QRect(40, 310, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.passwordLabel.setFont(font)
        self.passwordLabel.setObjectName("passwordLabel")
        self.label_2 = QtWidgets.QLabel(signUp)
        self.label_2.setGeometry(QtCore.QRect(40, 490, 151, 21))
        font = QtGui.QFont()
        font.setUnderline(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.usernameLabel_2 = QtWidgets.QLabel(signUp)
        self.usernameLabel_2.setGeometry(QtCore.QRect(40, 120, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.usernameLabel_2.setFont(font)
        self.usernameLabel_2.setObjectName("usernameLabel_2")

        self.retranslateUi(signUp)
        QtCore.QMetaObject.connectSlotsByName(signUp)

    def retranslateUi(self, signUp):
        _translate = QtCore.QCoreApplication.translate
        signUp.setWindowTitle(_translate("signUp", "EconoMystique"))
        self.pushButton.setText(_translate("signUp", "SIGN IN"))
        self.usernameLabel.setText(_translate("signUp", "Username:"))
        self.loginButton.setText(_translate("signUp", "Login"))
        self.loginLabel.setText(_translate("signUp", "SIGN IN"))
        self.passwordLabel.setText(_translate("signUp", "Password:"))
        self.label_2.setText(_translate("signUp", "I already have an account"))
        self.usernameLabel_2.setText(_translate("signUp", "Email:"))
