# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Joumongo\Documents\Economystique\wastage.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_decWastage(object):
    def setupUi(self, decWastage):
        decWastage.setObjectName("decWastage")
        decWastage.resize(600, 300)
        decWastage.setStyleSheet("background-color: #f4f4ec;")
        self.buttonBox = QtWidgets.QDialogButtonBox(decWastage)
        self.buttonBox.setGeometry(QtCore.QRect(10, 230, 581, 51))
        self.buttonBox.setStyleSheet("QPushButton{\n"
"    background: #365b6d;\n"
"    color: white;\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius:10px;\n"
"    border-color: black;\n"
"    padding: 5px;\n"
"    height: 25px;\n"
"    width: 100px;\n"
"    font-size: 16px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #53786d;\n"
"    border: 2px solid black;\n"
"}\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background-color: #365b6d;\n"
"}")
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.teAmount = QtWidgets.QLineEdit(decWastage)
        self.teAmount.setGeometry(QtCore.QRect(160, 89, 421, 41))
        self.teAmount.setStyleSheet("background: white;\n"
"border: 1px solid black;\n"
"border-radius: 5px;")
        self.teAmount.setAlignment(QtCore.Qt.AlignCenter)
        self.teAmount.setObjectName("teAmount")
        self.verticalLayoutWidget = QtWidgets.QWidget(decWastage)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 29, 131, 111))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.cbItems = QtWidgets.QComboBox(decWastage)
        self.cbItems.setGeometry(QtCore.QRect(158, 30, 421, 41))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        self.cbItems.setFont(font)
        self.cbItems.setStyleSheet("background: white;")
        self.cbItems.setObjectName("cbItems")
        self.lblUnit = QtWidgets.QLabel(decWastage)
        self.lblUnit.setGeometry(QtCore.QRect(160, 140, 421, 41))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        self.lblUnit.setFont(font)
        self.lblUnit.setText("")
        self.lblUnit.setAlignment(QtCore.Qt.AlignCenter)
        self.lblUnit.setObjectName("lblUnit")

        self.retranslateUi(decWastage)
        self.buttonBox.accepted.connect(decWastage.accept) # type: ignore
        self.buttonBox.rejected.connect(decWastage.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(decWastage)

    def retranslateUi(self, decWastage):
        _translate = QtCore.QCoreApplication.translate
        decWastage.setWindowTitle(_translate("decWastage", "Wastage"))
        self.teAmount.setPlaceholderText(_translate("decWastage", "Enter a number..."))
        self.label.setText(_translate("decWastage", "Item"))
        self.label_2.setText(_translate("decWastage", "Quantity"))
